//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace Acorisoft.FutureGL.Forest.Effects.Bitmaps
{
	
	public class TintEffect : ShaderEffect 
	{
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(TintEffect), 0);
		public static readonly DependencyProperty TintProperty = DependencyProperty.Register(nameof(Tint),
			typeof(Color), 
			typeof(TintEffect), 
			new UIPropertyMetadata(Color.FromArgb(255, 0, 0, 0), PixelShaderConstantCallback(0)));
		
		public TintEffect()
		{
			PixelShader pixelShader = new PixelShader
			{
				UriSource = new Uri("pack://application:,,,/Forest;component/Effects/Bitmaps/TintEffect.ps", UriKind.RelativeOrAbsolute)
			};
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(TintProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		public Color Tint {
			get {
				return ((Color)(this.GetValue(TintProperty)));
			}
			set {
				this.SetValue(TintProperty, value);
			}
		}
	}
}
