
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Services;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class MusicEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new MusicEngine();
        }
    }
}
