
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Documents;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class ComposeEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new ComposeEngine();
        }
    }
}
