
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.Keywords;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class KeywordEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new KeywordEngine();
        }
    }
}
