
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.FantasyProjects;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class ProjectEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new ProjectEngine();
        }
    }
}
