
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.Socials;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class SocialEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new SocialEngine();
        }
    }
}
