
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.Templates;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class TemplateEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new TemplateEngine();
        }
    }
}
