
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.Universe;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class UniverseEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new UniverseEngine();
        }
    }
}
