
// <auto-generated/>

using Acorisoft.FutureGL.MigaDB.Data.Worldview;

namespace Acorisoft.FutureGL.MigaDB.Tests.Engines.Data
{
    [TestClass, TestCategory("Engine")]
    public class WorldViewEngineFixture
    {
        public void InitializeThisUnitTest()
        {
            var vm = new WorldViewEngine();
        }
    }
}
