//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorisoft.Miga.Doc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorisoft.Miga.Doc.DocSR", typeof(DocSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经添加重复的模组.
        /// </summary>
        public static string ErrMsg_DuplicatedDataPart {
            get {
                return ResourceManager.GetString("ErrMsg_DuplicatedDataPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数{0}为空.
        /// </summary>
        public static string ErrMsg_ParameterEmptyName {
            get {
                return ResourceManager.GetString("ErrMsg_ParameterEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 世界观已存在.
        /// </summary>
        public static string ErrMsg_RepositoryExists {
            get {
                return ResourceManager.GetString("ErrMsg_RepositoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 世界观已经损坏.
        /// </summary>
        public static string ErrMsg_RepositoryFormatIsBad {
            get {
                return ResourceManager.GetString("ErrMsg_RepositoryFormatIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 世界观已经被删除.
        /// </summary>
        public static string ErrMsg_RepositoryHasBeenRemoved {
            get {
                return ResourceManager.GetString("ErrMsg_RepositoryHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 世界观为空或者不存在.
        /// </summary>
        public static string ErrMsg_RepositoryNotExists {
            get {
                return ResourceManager.GetString("ErrMsg_RepositoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mgdoc.
        /// </summary>
        public static string Ext_Document {
            get {
                return ResourceManager.GetString("Ext_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .png.
        /// </summary>
        public static string Ext_Modules {
            get {
                return ResourceManager.GetString("Ext_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mgdb.
        /// </summary>
        public static string Ext_Repository {
            get {
                return ResourceManager.GetString("Ext_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mgidx.
        /// </summary>
        public static string Ext_Repository_Index {
            get {
                return ResourceManager.GetString("Ext_Repository_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未命名.
        /// </summary>
        public static string Field_Untitle {
            get {
                return ResourceManager.GetString("Field_Untitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定|*.png.
        /// </summary>
        public static string Filter_Document {
            get {
                return ResourceManager.GetString("Filter_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组|*.png.
        /// </summary>
        public static string Filter_Modules {
            get {
                return ResourceManager.GetString("Filter_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 世界观|*.mgidx.
        /// </summary>
        public static string Filter_Repository_Index {
            get {
                return ResourceManager.GetString("Filter_Repository_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string Text_Author {
            get {
                return ResourceManager.GetString("Text_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题曲.
        /// </summary>
        public static string Title_MainTheme {
            get {
                return ResourceManager.GetString("Title_MainTheme", resourceCulture);
            }
        }
    }
}
